### ISSUE TITLE
First Level Tree Labels

### ISSUE THREAD

**Issue by kaylavix** [openwichita/openbudgetwichita#12]
Britten & Kayla would like to see first-level tree labels on individual the now-unlabeled main quadrants. Right now, hover only shows you the name of the second-level box you happen to be over, not the first level. See gray box on the right: hover shows level-two information.

![screen shot 2017-03-04 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/24445724/23582114/c1f3c364-00e8-11e7-93ad-8661f79b16cd.png)

**Comment by sethetter** [comment]
This should be fixed after open oakland merge
