### ISSUE TITLE
Duplicated Levels - Library

### ISSUE THREAD

**Issue by kaylavix** [openwichita/openbudgetwichita#14]
Second-level of library is a duplicated number with a different title. Since level two is a duplication of level one, hover in level one doesn't show breakdowns.

![screen shot 2017-03-04 at 2 47 25 pm](https://cloud.githubusercontent.com/assets/24445724/23582146/867442a4-00e9-11e7-89dc-ee235e599a83.png)

**Comment by sethetter** [comment]
Looks like it's resolved! https://budget.openwichita.com/2017-adopted-budget-tree.html#2017.expense.generalfund.library.administrativeservices
