### ISSUE TITLE
Duplicated Levels - Human Resources

### ISSUE THREAD

**Issue by kaylavix** [openwichita/openbudgetwichita#15]
Same problem as library.

![screen shot 2017-03-04 at 2 49 38 pm](https://cloud.githubusercontent.com/assets/24445724/23582161/d48f33a4-00e9-11e7-970c-326d30022b8a.png)

**Comment by sethetter** [comment]
Looks like there's a kind of useless level here, but I think that's just the nature of the hierarchy. Shouldn't be an issue! https://budget.openwichita.com/2017-adopted-budget-tree.html#2017.expense.generalfund.humanresources.humanresources-operations
