### ISSUE TITLE
Duplicated Levels - Metropolitan Planning

### ISSUE THREAD

**Issue by kaylavix** [openwichita/openbudgetwichita#16]
![screen shot 2017-03-04 at 2 50 30 pm](https://cloud.githubusercontent.com/assets/24445724/23582172/f580d900-00e9-11e7-9bc9-adb9deeb6968.png)

**Comment by sethetter** [comment]
Merged in Open Oakland code and now the flow diagram is in master!

check `_src/templates/flow.jade` and `_src/2016-17-adjusted-budget-flow.jade` to start!

**Comment by sethetter** [comment]
Looks like it's resolved! -- https://budget.openwichita.com/2017-adopted-budget-tree.html#2017.expense.city/countyjointoperationsfund.metropolitanplanning
