### ISSUE TITLE
Something Fishy with City Council (Also potential duplication)

### ISSUE THREAD

**Issue by kaylavix** [openwichita/openbudgetwichita#17]
Squished text at the bottom? Same issue with duplication at level 1.

![screen shot 2017-03-04 at 2 51 41 pm](https://cloud.githubusercontent.com/assets/24445724/23582181/297c2d90-00ea-11e7-892f-080e8f827644.png)

**Comment by sethetter** [comment]
I think the new tree diagram has this issue resolved -> https://budget.openwichita.com/2017-adopted-budget-tree.html#2017.expense.generalfund.citycouncil
