### ISSUE TITLE
Finish up flow diagram page

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#28]
Let's make sure..

- Copy on the page is accurate, including references to Wichita
- Make sure it says "Adopted Budget" instead of "Adjusted" or anything else
- Filename reflects data (2017-adopted-budget)
- Anything else you all can find!

The file is currently at  `_src/2016-17-adjusted-budget-flow.jade`.

**Comment by ydkahin** [comment]
- Should the title be _2017 Adopted Budget_?
- Also, is the `2017__adopted.csv` file Wichita's or Oakland's? I ask this since at the bottom the City of Oakland is cited. If so, do we remove the citations at the bottom?

**Comment by sethetter** [comment]
@ydkahin yes, that's the correct title, and yes that's Wichita's data file, the copy on the page just hasn't been updated yet.

**Comment by sethetter** [comment]
Done with #36
