### ISSUE TITLE
What domain do we want to launch this at?

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#3]
openbudgetwichita.com?

Also considering any promotional tactics would be helpful! Post ideas here.

**Comment by br0xen** [comment]
Is openbudgetwichita.com really better than budget.openwichita.com?
Does that make it sound too much like it's the budget for OpenWichita? Is it worth not paying $10-15/year for that?

**Comment by sethetter** [comment]
@br0xen I think I like budget.openwichita.com, when someone goes to the site it will be pretty clear that it's municipal budget info.

**Comment by sethetter** [comment]
Staging up at budget.openwichita.com, I think we'll stick with that for when it's all ready too!
