### ISSUE TITLE
Update visualizations list

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#33]
Update `_src/budget-visuals.jade` to show just our currently available Wichita visualizations. Over time we'll add past years to this page as well.

It should include..
- 2017-adopted-budget-tree
- 2017-adopted-budget-flow
- budget-process

**Comment by ydkahin** [comment]
Couldn't find the 2017-adopted-budget-flow page.

**Comment by ydkahin** [comment]
#28 precedes this.

**Comment by ydkahin** [comment]
Also, we need updated preview images for those 3 pages.

**Comment by sethetter** [comment]
Almost done with #36, but still need preview images so I'm leaving this open!
