### ISSUE TITLE
Updated preview images for visualizations

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#37]
Just need to..

- Take a screen shot of the visualization (tree, flow, and timeline)
- Crop it down to a common size (reference ones on homepage now for what sizes to use)
- Put them in the `_src/images/` folder and update references on the homepage and on the visualizations list.

**Comment by kaylavix** [comment]
I could do this. What file type is preferred?

**Comment by Mottie** [comment]
I've already updated the timeline thumb ([ref](https://github.com/openwichita/openbudgetwichita/commit/e15ee9eabf05221fd20d479820776521115db9f4)). The radar thumb would need to be updated after we get the 2016 data and PR #41 gets merged which has the corrected link to the radar data.

**Comment by kaylavix** [comment]
Ok, I'll wait then.
