### ISSUE TITLE
Link Issues

### ISSUE THREAD

**Issue by katherinepdavis** [openwichita/openbudgetwichita#58]
Several links give me a certificate error:

![image](https://user-images.githubusercontent.com/30677505/28904728-9d3aaacc-77d2-11e7-8748-96404bea7cdb.png)

- Join us in Slack (https://openwichita.com/slack) - main page and footer
- Source for data (https://opendata.wichita.gov/) - Tree and Flow viz pages

Code for OKC link is missing the : after http and doesn't work.

**Comment by sethetter** [comment]
@katherinepdavis good catch! The `https` links for `openwichita.com` won't work because GitHub Pages doesn't support SSL :(

In the future I'll switch that site over to netlify so we can get free SSL. For now, the fix that @Mottie pushed up will take care of these things!
