### ISSUE TITLE
When first drilling down into a category, labels do not appear on treemaps

### ISSUE THREAD

**Issue by infernocloud** [openwichita/openbudgetwichita#6]
Page example: http://openbudgetoakland.org/2016-17-adjusted-budget-tree.html#fy16-17.expense.generalfund:generalpurpose
Browser: Chrome Version 54.0.2840.99 m (64-bit)

![openbudget-treemap-bug](https://cloud.githubusercontent.com/assets/1633850/20780966/fb6baa8c-b744-11e6-8ea3-ec3d00bb7280.PNG)

**Comment by br0xen** [comment]
It's worth checking the updated code from OKC on this. That's what I was looking at when I mentioned that it was working for me.

**Comment by sethetter** [comment]
It looks like this is resolved, can someone else confirm! @infernocloud?
