### ISSUE TITLE
Table sorting on tree view

### ISSUE THREAD

**Issue by sethetter** [openwichita/openbudgetwichita#9]
The table showing items below the tree view should be sortable by column. Probably a jQuery plugin that could do this.

**Comment by imonthercks** [comment]
Not sure if anyone else is working on this yet, but I thought I would take a stab at it.

**Comment by sethetter** [comment]
@imonthercks it's all yours!

**Comment by imonthercks** [comment]
Created Pull Request #11 to add Table sorting on the tree view
